INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (1001,'เขต พระนคร','Phra Nakhon',1,NULL,NULL),
	 (1002,'เขต ดุสิต','Dusit',1,NULL,NULL),
	 (1003,'เขต หนองจอก','Nong Chok',1,NULL,NULL),
	 (1004,'เขต บางรัก','Bang Rak',1,NULL,NULL),
	 (1005,'เขต บางเขน','Bang Khen',1,NULL,NULL),
	 (1006,'เขต บางกะปิ','Bang Kapi',1,NULL,NULL),
	 (1007,'เขต ปทุมวัน','Pathum Wan',1,NULL,NULL),
	 (1008,'เขต ป้อมปราบศัตรูพ่าย','Pom Prap Sattruphai',1,NULL,NULL),
	 (1009,'เขต พระโขนง','Phra Khanong',1,NULL,NULL),
	 (1010,'เขต มีนบุรี','Min Buri',1,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (1011,'เขต ลาดกระบัง','Lat Krabang',1,NULL,NULL),
	 (1012,'เขต ยานนาวา','Yannawa',1,NULL,NULL),
	 (1013,'เขต สัมพันธวงศ์','Samphanthawong',1,NULL,NULL),
	 (1014,'เขต พญาไท','Phaya Thai',1,NULL,NULL),
	 (1015,'เขต ธนบุรี','Thon Buri',1,NULL,NULL),
	 (1016,'เขต บางกอกใหญ่','Bangkok Yai',1,NULL,NULL),
	 (1017,'เขต ห้วยขวาง','Huai Khwang',1,NULL,NULL),
	 (1018,'เขต คลองสาน','Khlong San',1,NULL,NULL),
	 (1019,'เขต ตลิ่งชัน','Taling Chan',1,NULL,NULL),
	 (1020,'เขต บางกอกน้อย','Bangkok Noi',1,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (1021,'เขต บางขุนเทียน','Bang Khun Thian',1,NULL,NULL),
	 (1022,'เขต ภาษีเจริญ','Phasi Charoen',1,NULL,NULL),
	 (1023,'เขต หนองแขม','Nong Khaem',1,NULL,NULL),
	 (1024,'เขต ราษฎร์บูรณะ','Rat Burana',1,NULL,NULL),
	 (1025,'เขต บางพลัด','Bang Phlat',1,NULL,NULL),
	 (1026,'เขต ดินแดง','Din Daeng',1,NULL,NULL),
	 (1027,'เขต บึงกุ่ม','Bung Kum',1,NULL,NULL),
	 (1028,'เขต สาทร','Sa Thon',1,NULL,NULL),
	 (1029,'เขต บางซื่อ','Bang Su',1,NULL,NULL),
	 (1030,'เขต จตุจักร','Chatuchak',1,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (1031,'เขต บางคอแหลม','Bang Kho Laem',1,NULL,NULL),
	 (1032,'เขต ประเวศ','Prawet',1,NULL,NULL),
	 (1033,'เขต คลองเตย','Khlong Toei',1,NULL,NULL),
	 (1034,'เขต สวนหลวง','Suan Luang',1,NULL,NULL),
	 (1035,'เขต จอมทอง','Chom Thong',1,NULL,NULL),
	 (1036,'เขต ดอนเมือง','Don Mueang',1,NULL,NULL),
	 (1037,'เขต ราชเทวี','Rat Thewi',1,NULL,NULL),
	 (1038,'เขต ลาดพร้าว','Lat Phrao',1,NULL,NULL),
	 (1039,'เขต วัฒนา','Watthana',1,NULL,NULL),
	 (1040,'เขต บางแค','Bang Khae',1,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (1041,'เขต หลักสี่','Lak Si',1,NULL,NULL),
	 (1042,'เขต สายไหม','Sai Mai',1,NULL,NULL),
	 (1043,'เขต คันนายาว','Khanna Yao',1,NULL,NULL),
	 (1044,'เขต สะพานสูง','Saphan Sung',1,NULL,NULL),
	 (1045,'เขต วังทองหลาง','Wang Thong Lang',1,NULL,NULL),
	 (1046,'เขต คลองสามวา','Khlong Sam Wa',1,NULL,NULL),
	 (1047,'เขต บางนา','Bang Na',1,NULL,NULL),
	 (1048,'เขต ทวีวัฒนา','Thawi Watthana',1,NULL,NULL),
	 (1049,'เขต ทุ่งครุ','Thung Khu',1,NULL,NULL),
	 (1050,'เขต บางบอน','Bang Bon',1,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (1101,'เมืองสมุทรปราการ','Mueang Samut Prakan',2,NULL,NULL),
	 (1102,'บางบ่อ','Bang Bo',2,NULL,NULL),
	 (1103,'บางพลี','Bang Phli',2,NULL,NULL),
	 (1104,'พระประแดง','Phra Pradaeng',2,NULL,NULL),
	 (1105,'พระสมุทรเจดีย์','Phra Samut Chedi',2,NULL,NULL),
	 (1106,'บางเสาธง','Bang Sao Thong',2,NULL,NULL),
	 (1201,'เมืองนนทบุรี','Mueang Nonthaburi',3,NULL,NULL),
	 (1202,'บางกรวย','Bang Kruai',3,NULL,NULL),
	 (1203,'บางใหญ่','Bang Yai',3,NULL,NULL),
	 (1204,'บางบัวทอง','Bang Bua Thong',3,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (1205,'ไทรน้อย','Sai Noi',3,NULL,NULL),
	 (1206,'ปากเกร็ด','Pak Kret',3,NULL,NULL),
	 (1301,'เมืองปทุมธานี','Mueang Pathum Thani',4,NULL,NULL),
	 (1302,'คลองหลวง','khlong Luang',4,NULL,NULL),
	 (1303,'ธัญบุรี','Thanyaburi',4,NULL,NULL),
	 (1304,'หนองเสือ','Nong Suea',4,NULL,NULL),
	 (1305,'ลาดหลุมแก้ว','Lat Lum Kaeo',4,NULL,NULL),
	 (1306,'ลำลูกกา','Lam Luk Ka',4,NULL,NULL),
	 (1307,'สามโคก','Sam Khok',4,NULL,NULL),
	 (1401,'พระนครศรีอยุธยา','Phra Nakhon Si Ayutthaya',5,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (1402,'ท่าเรือ','Tha Ruea',5,NULL,NULL),
	 (1403,'นครหลวง','Nakhon Luang',5,NULL,NULL),
	 (1404,'บางไทร','Bang Sai',5,NULL,NULL),
	 (1405,'บางบาล','Bang Ban',5,NULL,NULL),
	 (1406,'บางปะอิน','Bang Pa-in',5,NULL,NULL),
	 (1407,'บางปะหัน','Bang Pahan',5,NULL,NULL),
	 (1408,'ผักไห่','Phak Hai',5,NULL,NULL),
	 (1409,'ภาชี','Phachi',5,NULL,NULL),
	 (1410,'ลาดบัวหลวง','Lat Bua Luang',5,NULL,NULL),
	 (1411,'วังน้อย','Wang Noi',5,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (1412,'เสนา','Sena',5,NULL,NULL),
	 (1413,'บางซ้าย','Bang Sai',5,NULL,NULL),
	 (1414,'อุทัย','Uthai',5,NULL,NULL),
	 (1415,'มหาราช','Maha Rat',5,NULL,NULL),
	 (1416,'บ้านแพรก','Ban Phraek',5,NULL,NULL),
	 (1501,'เมืองอ่างทอง','Mueang Ang Thong',6,NULL,NULL),
	 (1502,'ไชโย','Chaiyo',6,NULL,NULL),
	 (1503,'ป่าโมก','Pa Mok',6,NULL,NULL),
	 (1504,'โพธิ์ทอง','Pho Thong',6,NULL,NULL),
	 (1505,'แสวงหา','Sawaeng Ha',6,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (1506,'วิเศษชัยชาญ','Wiset Chai Chan',6,NULL,NULL),
	 (1507,'สามโก้','Samko',6,NULL,NULL),
	 (1601,'เมืองลพบุรี','Mueang Lop Buri',7,NULL,NULL),
	 (1602,'พัฒนานิคม','Phatthana Nikhom',7,NULL,NULL),
	 (1603,'โคกสำโรง','Khok Samrong',7,NULL,NULL),
	 (1604,'ชัยบาดาล','Chai Badan',7,NULL,NULL),
	 (1605,'ท่าวุ้ง','Tha Wung',7,NULL,NULL),
	 (1606,'บ้านหมี่','Ban Mi',7,NULL,NULL),
	 (1607,'ท่าหลวง','Tha Luang',7,NULL,NULL),
	 (1608,'สระโบสถ์','Sa Bot',7,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (1609,'โคกเจริญ','Khok Charoen',7,NULL,NULL),
	 (1610,'ลำสนธิ','Lam Sonthi',7,NULL,NULL),
	 (1611,'หนองม่วง','Nong Muang',7,NULL,NULL),
	 (1701,'เมืองสิงห์บุรี','Mueang Sing Buri',8,NULL,NULL),
	 (1702,'บางระจัน','Bang Rachan',8,NULL,NULL),
	 (1703,'ค่ายบางระจัน','Khai Bang Rachan',8,NULL,NULL),
	 (1704,'พรหมบุรี','Phrom Buri',8,NULL,NULL),
	 (1705,'ท่าช้าง','Tha Chang',8,NULL,NULL),
	 (1706,'อินทร์บุรี','In Buri',8,NULL,NULL),
	 (1801,'เมืองชัยนาท','Mueang Chai Nat',9,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (1802,'มโนรมย์','Manorom',9,NULL,NULL),
	 (1803,'วัดสิงห์','Wat Sing',9,NULL,NULL),
	 (1804,'สรรพยา','Sapphaya',9,NULL,NULL),
	 (1805,'สรรคบุรี','Sankhaburi',9,NULL,NULL),
	 (1806,'หันคา','Hankha',9,NULL,NULL),
	 (1807,'หนองมะโมง','Nong Mamong',9,NULL,NULL),
	 (1808,'เนินขาม','Noen Kham',9,NULL,NULL),
	 (1901,'เมืองสระบุรี','Mueang Saraburi',10,NULL,NULL),
	 (1902,'แก่งคอย','Kaeng Khoi',10,NULL,NULL),
	 (1903,'หนองแค','Nong Khae',10,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (1904,'วิหารแดง','Wihan Daeng',10,NULL,NULL),
	 (1905,'หนองแซง','Nong Saeng',10,NULL,NULL),
	 (1906,'บ้านหมอ','Ban Mo',10,NULL,NULL),
	 (1907,'ดอนพุด','Don Phut',10,NULL,NULL),
	 (1908,'หนองโดน','Nong Don',10,NULL,NULL),
	 (1909,'พระพุทธบาท','Phra Phutthabat',10,NULL,NULL),
	 (1910,'เสาไห้','Sao Hai',10,NULL,NULL),
	 (1911,'มวกเหล็ก','Muak Lek',10,NULL,NULL),
	 (1912,'วังม่วง','Wang Muang',10,NULL,NULL),
	 (1913,'เฉลิมพระเกียรติ','Chaloem Phra Kiet',10,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (2001,'เมืองชลบุรี','Mueang Chon Buri',11,NULL,NULL),
	 (2002,'บ้านบึง','Ban Bueng',11,NULL,NULL),
	 (2003,'หนองใหญ่','Nong Yai',11,NULL,NULL),
	 (2004,'บางละมุง','Bang Lamung',11,NULL,NULL),
	 (2005,'พานทอง','Phan Thong',11,NULL,NULL),
	 (2006,'พนัสนิคม','Phanat Nikhom',11,NULL,NULL),
	 (2007,'ศรีราชา','Si Racha',11,NULL,NULL),
	 (2008,'เกาะสีชัง','Ko Sichang',11,NULL,NULL),
	 (2009,'สัตหีบ','Sattahip',11,NULL,NULL),
	 (2010,'บ่อทอง','Bo Thong',11,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (2011,'เกาะจันทร์','Ko Chan',11,NULL,NULL),
	 (2101,'เมืองระยอง','Mueang Rayong',12,NULL,NULL),
	 (2102,'บ้านฉาง','Ban Chang',12,NULL,NULL),
	 (2103,'แกลง','Klaeng',12,NULL,NULL),
	 (2104,'วังจันทร์','Wang Chan',12,NULL,NULL),
	 (2105,'บ้านค่าย','Ban Khai',12,NULL,NULL),
	 (2106,'ปลวกแดง','Pluak Daeng',12,NULL,NULL),
	 (2107,'เขาชะเมา','Khao Chamao',12,NULL,NULL),
	 (2108,'นิคมพัฒนา','Nikhom Phatthana',12,NULL,NULL),
	 (2201,'เมืองจันทบุรี','Mueang Chanthaburi',13,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (2202,'ขลุง','Khlung',13,NULL,NULL),
	 (2203,'ท่าใหม่','Tha Mai',13,NULL,NULL),
	 (2204,'โป่งน้ำร้อน','Pong Nam Ron',13,NULL,NULL),
	 (2205,'มะขาม','Makham',13,NULL,NULL),
	 (2206,'แหลมสิงห์','Laem Sing',13,NULL,NULL),
	 (2207,'สอยดาว','Soi Dao',13,NULL,NULL),
	 (2208,'แก่งหางแมว','Kaeng Hang Maeo',13,NULL,NULL),
	 (2209,'นายายอาม','Na Yai Am',13,NULL,NULL),
	 (2210,'เขาคิชฌกูฏ','Khao Khitchakut',13,NULL,NULL),
	 (2301,'เมืองตราด','Mueang Trat',14,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (2302,'คลองใหญ่','Khlong Yai',14,NULL,NULL),
	 (2303,'เขาสมิง','Khao Saming',14,NULL,NULL),
	 (2304,'บ่อไร่','Bo Rai',14,NULL,NULL),
	 (2305,'แหลมงอบ','Laem Ngop',14,NULL,NULL),
	 (2306,'เกาะกูด','Ko Kut',14,NULL,NULL),
	 (2307,'เกาะช้าง','Ko Chang',14,NULL,NULL),
	 (2401,'เมืองฉะเชิงเทรา','Mueang Chachoengsao',15,NULL,NULL),
	 (2402,'บางคล้า','Bang Khla',15,NULL,NULL),
	 (2403,'บางน้ำเปรี้ยว','Bang Nam Priao',15,NULL,NULL),
	 (2404,'บางปะกง','Bang Pakong',15,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (2405,'บ้านโพธิ์','Ban Pho',15,NULL,NULL),
	 (2406,'พนมสารคาม','Phanom Sarakham',15,NULL,NULL),
	 (2407,'ราชสาส์น','Ratchasan',15,NULL,NULL),
	 (2408,'สนามชัยเขต','Sanam Chai Khet',15,NULL,NULL),
	 (2409,'แปลงยาว','Pleang Yao',15,NULL,NULL),
	 (2410,'ท่าตะเกียบ','Tha Takiap',15,NULL,NULL),
	 (2411,'คลองเขื่อน','Khlong Khuean',15,NULL,NULL),
	 (2501,'เมืองปราจีนบุรี','Mueang Prachin Buri',16,NULL,NULL),
	 (2502,'กบินทร์บุรี','Kabin Buri',16,NULL,NULL),
	 (2503,'นาดี','Na Di',16,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (2506,'บ้านสร้าง','Ban Sang',16,NULL,NULL),
	 (2507,'ประจันตคาม','Prachantakham',16,NULL,NULL),
	 (2508,'ศรีมหาโพธิ','Si Maha Phot',16,NULL,NULL),
	 (2509,'ศรีมโหสถ','Si Mahosot',16,NULL,NULL),
	 (2601,'เมืองนครนายก','Mueang Nakhon Nayok',17,NULL,NULL),
	 (2602,'ปากพลี','Pak Phli',17,NULL,NULL),
	 (2603,'บ้านนา','Ban Na',17,NULL,NULL),
	 (2604,'องครักษ์','Ongkharak',17,NULL,NULL),
	 (2701,'เมืองสระแก้ว','Mueang Sa Kaeo',18,NULL,NULL),
	 (2702,'คลองหาด','Khlong Hat',18,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (2703,'ตาพระยา','Ta Phraya',18,NULL,NULL),
	 (2704,'วังน้ำเย็น','Wang Nam Yen',18,NULL,NULL),
	 (2705,'วัฒนานคร','Watthana Nakhon',18,NULL,NULL),
	 (2706,'อรัญประเทศ','Aranyaprathet',18,NULL,NULL),
	 (2707,'เขาฉกรรจ์','Khao Chakan',18,NULL,NULL),
	 (2708,'โคกสูง','Khok Sung',18,NULL,NULL),
	 (2709,'วังสมบูรณ์','Wang Sombun',18,NULL,NULL),
	 (3001,'เมืองนครราชสีมา','Mueang Nakhon Ratchasima',19,NULL,NULL),
	 (3002,'ครบุรี','Khon Buri',19,NULL,NULL),
	 (3003,'เสิงสาง','Soeng Sang',19,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (3004,'คง','Khong',19,NULL,NULL),
	 (3005,'บ้านเหลื่อม','Ban Lueam',19,NULL,NULL),
	 (3006,'จักราช','Chakkarat',19,NULL,NULL),
	 (3007,'โชคชัย','Chok Chai',19,NULL,NULL),
	 (3008,'ด่านขุนทด','Dan Khun Thot',19,NULL,NULL),
	 (3009,'โนนไทย','Non Thai',19,NULL,NULL),
	 (3010,'โนนสูง','Non Sung',19,NULL,NULL),
	 (3011,'ขามสะแกแสง','Kham Sakaesaeng',19,NULL,NULL),
	 (3012,'บัวใหญ่','Bua Yai',19,NULL,NULL),
	 (3013,'ประทาย','Prathai',19,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (3014,'ปักธงชัย','Pak Thong Chai',19,NULL,NULL),
	 (3015,'พิมาย','Phimai',19,NULL,NULL),
	 (3016,'ห้วยแถลง','Huai Thalaeng',19,NULL,NULL),
	 (3017,'ชุมพวง','Chum Phuang',19,NULL,NULL),
	 (3018,'สูงเนิน','Sung Noen',19,NULL,NULL),
	 (3019,'ขามทะเลสอ','Kham Thale So',19,NULL,NULL),
	 (3020,'สีคิ้ว','Si Khio',19,NULL,NULL),
	 (3021,'ปากช่อง','Pak Chong',19,NULL,NULL),
	 (3022,'หนองบุญมาก','Nong Bunmak',19,NULL,NULL),
	 (3023,'แก้งสนามนาง','Kaeng Sanam Nang',19,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (3024,'โนนแดง','Non Daeng',19,NULL,NULL),
	 (3025,'วังน้ำเขียว','Wang Nam Khiao',19,NULL,NULL),
	 (3026,'เทพารักษ์','Thepharak',19,NULL,NULL),
	 (3027,'เมืองยาง','Mueang Yang',19,NULL,NULL),
	 (3028,'พระทองคำ','Phra Thong Kham',19,NULL,NULL),
	 (3029,'ลำทะเมนชัย','Lamtaman Chai',19,NULL,NULL),
	 (3030,'บัวลาย','Bua Lai',19,NULL,NULL),
	 (3031,'สีดา','Sida',19,NULL,NULL),
	 (3032,'เฉลิมพระเกียรติ','Chaloem Phra Kiet',19,NULL,NULL),
	 (3101,'เมืองบุรีรัมย์','Mueang Buri Ram',20,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (3102,'คูเมือง','Khu Mueang',20,NULL,NULL),
	 (3103,'กระสัง','Krasang',20,NULL,NULL),
	 (3104,'นางรอง','Nang Rong',20,NULL,NULL),
	 (3105,'หนองกี่','Nong Ki',20,NULL,NULL),
	 (3106,'ละหานทราย','Lahan Sai',20,NULL,NULL),
	 (3107,'ประโคนชัย','Prakhon Chai',20,NULL,NULL),
	 (3108,'บ้านกรวด','Ban Kruat',20,NULL,NULL),
	 (3109,'พุทไธสง','Phutthaisong',20,NULL,NULL),
	 (3110,'ลำปลายมาศ','Lam Plai Mat',20,NULL,NULL),
	 (3111,'สตึก','Satuek',20,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (3112,'ปะคำ','Pakham',20,NULL,NULL),
	 (3113,'นาโพธิ์','Na Pho',20,NULL,NULL),
	 (3114,'หนองหงส์','Nong Hong',20,NULL,NULL),
	 (3115,'พลับพลาชัย','Phlapphla Chai',20,NULL,NULL),
	 (3116,'ห้วยราช','Huai Rat',20,NULL,NULL),
	 (3117,'โนนสุวรรณ','Non Din Daeng',20,NULL,NULL),
	 (3118,'ชำนิ','Chamni',20,NULL,NULL),
	 (3119,'บ้านใหม่ไชยพจน์','Ban Mai Chaiyaphot',20,NULL,NULL),
	 (3120,'โนนดินแดง','Non Din Daeng',20,NULL,NULL),
	 (3121,'บ้านด่าน','Ban Dan',20,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (3122,'แคนดง','Khaen Dong',20,NULL,NULL),
	 (3123,'เฉลิมพระเกียรติ','Chaloem Phra Kiet',20,NULL,NULL),
	 (3201,'เมืองสุรินทร์','Mueang Surin',21,NULL,NULL),
	 (3202,'ชุมพลบุรี','Chumphon Buri',21,NULL,NULL),
	 (3203,'ท่าตูม','Tha Tum',21,NULL,NULL),
	 (3204,'จอมพระ','Chom Phra',21,NULL,NULL),
	 (3205,'ปราสาท','Prasat',21,NULL,NULL),
	 (3206,'กาบเชิง','Kap Choeng',21,NULL,NULL),
	 (3207,'รัตนบุรี','Rattanaburi',21,NULL,NULL),
	 (3208,'สนม','Sanom',21,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (3209,'ศีขรภูมิ','Sikhoraphum',21,NULL,NULL),
	 (3210,'สังขะ','Sangkha',21,NULL,NULL),
	 (3211,'ลำดวน','Lamduan',21,NULL,NULL),
	 (3212,'สำโรงทาบ','Samrong Thap',21,NULL,NULL),
	 (3213,'บัวเชด','Buachet',21,NULL,NULL),
	 (3214,'พนมดงรัก','Phanom Dong Rak',21,NULL,NULL),
	 (3215,'ศรีณรงค์','Si Narong',21,NULL,NULL),
	 (3216,'เขวาสินรินทร์','Khwao Sinarin',21,NULL,NULL),
	 (3217,'โนนนารายณ์','Non Narai',21,NULL,NULL),
	 (3301,'เมืองศรีสะเกษ','Mueang Si Sa Ket',22,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (3302,'ยางชุมน้อย','Yang Chum Noi',22,NULL,NULL),
	 (3303,'กันทรารมย์','Kanthararom',22,NULL,NULL),
	 (3304,'กันทรลักษ์','Kantharalak',22,NULL,NULL),
	 (3305,'ขุขันธ์','Khukhan',22,NULL,NULL),
	 (3306,'ไพรบึง','Phrai Bueng',22,NULL,NULL),
	 (3307,'ปรางค์กู่','Prang Ku',22,NULL,NULL),
	 (3308,'ขุนหาญ','Khun Han',22,NULL,NULL),
	 (3309,'ราษีไศล','Rasi Salai',22,NULL,NULL),
	 (3310,'อุทุมพรพิสัย','Uthumphon Phisai',22,NULL,NULL),
	 (3311,'บึงบูรพ์','Bueng Bun',22,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (3312,'ห้วยทับทัน','Huai Thap Than',22,NULL,NULL),
	 (3313,'โนนคูณ','Non Khun',22,NULL,NULL),
	 (3314,'ศรีรัตนะ','Si Rattana',22,NULL,NULL),
	 (3315,'น้ำเกลี้ยง','Nam Kliang',22,NULL,NULL),
	 (3316,'วังหิน','Wang Hin',22,NULL,NULL),
	 (3317,'ภูสิงห์','Phu Sing',22,NULL,NULL),
	 (3318,'เมืองจันทร์','Mueang Chan',22,NULL,NULL),
	 (3319,'เบญจลักษ์','Benchalak',22,NULL,NULL),
	 (3320,'พยุห์','Phayu',22,NULL,NULL),
	 (3321,'โพธิ์ศรีสุวรรณ','Pho Si Suwan',22,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (3322,'ศิลาลาด','Sila Lat',22,NULL,NULL),
	 (3401,'เมืองอุบลราชธานี','Mueang Ubon Ratchathani',23,NULL,NULL),
	 (3402,'ศรีเมืองใหม่','Si Mueang Mai',23,NULL,NULL),
	 (3403,'โขงเจียม','Khong Chiam',23,NULL,NULL),
	 (3404,'เขื่องใน','Khueang Nai',23,NULL,NULL),
	 (3405,'เขมราฐ','Khemarat',23,NULL,NULL),
	 (3407,'เดชอุดม','Det Udom',23,NULL,NULL),
	 (3408,'นาจะหลวย','Na Chaluai',23,NULL,NULL),
	 (3409,'น้ำยืน','Nam Yuen',23,NULL,NULL),
	 (3410,'บุณฑริก','Boontharik',23,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (3411,'ตระการพืชผล','Trakan Phuet Phon',23,NULL,NULL),
	 (3412,'กุดข้าวปุ้น','Kut Khaopun',23,NULL,NULL),
	 (3414,'ม่วงสามสิบ','Muang Sam Sip',23,NULL,NULL),
	 (3415,'วารินชำราบ','Warin Chamrap',23,NULL,NULL),
	 (3419,'พิบูลมังสาหาร','Phibun Mangsahan',23,NULL,NULL),
	 (3420,'ตาลสุม','Tan Sum',23,NULL,NULL),
	 (3421,'โพธิ์ไทร','Pho Sai',23,NULL,NULL),
	 (3422,'สำโรง','Samrong',23,NULL,NULL),
	 (3424,'ดอนมดแดง','Don Mot Daeng',23,NULL,NULL),
	 (3425,'สิรินธร','Sirindhorn',23,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (3426,'ทุ่งศรีอุดม','Thung Si Udom',23,NULL,NULL),
	 (3429,'นาเยีย','Na Yia',23,NULL,NULL),
	 (3430,'นาตาล','Na Tan',23,NULL,NULL),
	 (3431,'เหล่าเสือโก้ก','Lao Suea Kok',23,NULL,NULL),
	 (3432,'สว่างวีระวงศ์','Sawang Wirawong',23,NULL,NULL),
	 (3433,'น้ำขุ่น','Nam Khun',23,NULL,NULL),
	 (3501,'เมืองยโสธร','Mueang Yasothon',24,NULL,NULL),
	 (3502,'ทรายมูล','Sai Mun',24,NULL,NULL),
	 (3503,'กุดชุม','Kut Chum',24,NULL,NULL),
	 (3504,'คำเขื่อนแก้ว','Kham Khuean Kaeo',24,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (3505,'ป่าติ้ว','Pa Tio',24,NULL,NULL),
	 (3506,'มหาชนะชัย','Maha Chana Chai',24,NULL,NULL),
	 (3507,'ค้อวัง','Kho Wang',24,NULL,NULL),
	 (3508,'เลิงนกทา','Loeng Nok Tha',24,NULL,NULL),
	 (3509,'ไทยเจริญ','Thai Charoen',24,NULL,NULL),
	 (3601,'เมืองชัยภูมิ','Mueang Chaiyaphum',25,NULL,NULL),
	 (3602,'บ้านเขว้า','Ban Khwao',25,NULL,NULL),
	 (3603,'คอนสวรรค์','Khon Sawan',25,NULL,NULL),
	 (3604,'เกษตรสมบูรณ์','Kaset Sombun',25,NULL,NULL),
	 (3605,'หนองบัวแดง','Nong Bua Daeng',25,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (3606,'จัตุรัส','Chatturat',25,NULL,NULL),
	 (3607,'บำเหน็จณรงค์','Bamnet Narong',25,NULL,NULL),
	 (3608,'หนองบัวระเหว','Nong Bua Rawe',25,NULL,NULL),
	 (3609,'เทพสถิต','Thep Sathit',25,NULL,NULL),
	 (3610,'ภูเขียว','Phu Khiao',25,NULL,NULL),
	 (3611,'บ้านแท่น','Ban Thaen',25,NULL,NULL),
	 (3612,'แก้งคร้อ','Kaeng Khro',25,NULL,NULL),
	 (3613,'คอนสาร','Khon San',25,NULL,NULL),
	 (3614,'ภักดีชุมพล','Phakdi Chumphon',25,NULL,NULL),
	 (3615,'เนินสง่า','Noen Sa-nga',25,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (3616,'ซับใหญ่','Sap Yai',25,NULL,NULL),
	 (3701,'เมืองอำนาจเจริญ','Mueang Amnat Charoen',26,NULL,NULL),
	 (3702,'ชานุมาน','Chanuman',26,NULL,NULL),
	 (3703,'ปทุมราชวงศา','Pathum Ratchawongsa',26,NULL,NULL),
	 (3704,'พนา','Phana',26,NULL,NULL),
	 (3705,'เสนางคนิคม','Senangkhanikhom',26,NULL,NULL),
	 (3706,'หัวตะพาน','Hua Taphan',26,NULL,NULL),
	 (3707,'ลืออำนาจ','Lue Amnat',26,NULL,NULL),
	 (3801,'บึงกาฬ','Bueng Kan',27,NULL,NULL),
	 (3802,'พรเจริญ','Phon Charoen',27,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (3803,'โซ่พิสัย','So Phisai',27,NULL,NULL),
	 (3804,'เซกา','Seka',27,NULL,NULL),
	 (3805,'ปากคาด','Pak Khat',27,NULL,NULL),
	 (3806,'บึงโขงหลง','Bueng Khong Long',27,NULL,NULL),
	 (3807,'ศรีวิไล','Si Wilai',27,NULL,NULL),
	 (3808,'บุ่งคล้า','Bung Khla',27,NULL,NULL),
	 (3901,'เมืองหนองบัวลำภู','Mueang Nong Bua Lam Phu',28,NULL,NULL),
	 (3902,'นากลาง','Na Klang',28,NULL,NULL),
	 (3903,'โนนสัง','Non Sang',28,NULL,NULL),
	 (3904,'ศรีบุญเรือง','Si Bun Rueang',28,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (3905,'สุวรรณคูหา','Suwannakhuha',28,NULL,NULL),
	 (3906,'นาวัง','Na Wang',28,NULL,NULL),
	 (4001,'เมืองขอนแก่น','Mueang Khon Kaen',29,NULL,NULL),
	 (4002,'บ้านฝาง','Ban Fang',29,NULL,NULL),
	 (4003,'พระยืน','Phra Yuen',29,NULL,NULL),
	 (4004,'หนองเรือ','Nong Ruea',29,NULL,NULL),
	 (4005,'ชุมแพ','Chum Phae',29,NULL,NULL),
	 (4006,'สีชมพู','Si Chomphu',29,NULL,NULL),
	 (4007,'น้ำพอง','Nam Phong',29,NULL,NULL),
	 (4008,'อุบลรัตน์','Ubolratana',29,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (4009,'กระนวน','Kranuan',29,NULL,NULL),
	 (4010,'บ้านไผ่','Ban Phai',29,NULL,NULL),
	 (4011,'เปือยน้อย','Pueai Noi',29,NULL,NULL),
	 (4012,'พล','Phon',29,NULL,NULL),
	 (4013,'แวงใหญ่','Waeng Yai',29,NULL,NULL),
	 (4014,'แวงน้อย','Waeng Noi',29,NULL,NULL),
	 (4015,'หนองสองห้อง','Nong Song Hong',29,NULL,NULL),
	 (4016,'ภูเวียง','Phu Wiang',29,NULL,NULL),
	 (4017,'มัญจาคีรี','Mancha Khiri',29,NULL,NULL),
	 (4018,'ชนบท','Chonnabot',29,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (4019,'เขาสวนกวาง','Khao Suan Kwang',29,NULL,NULL),
	 (4020,'ภูผาม่าน','Phu Phaman',29,NULL,NULL),
	 (4021,'ซำสูง','Sam Sung',29,NULL,NULL),
	 (4022,'โคกโพธิ์ไชย','Khok Pho Chai',29,NULL,NULL),
	 (4023,'หนองนาคำ','Nong Na Kham',29,NULL,NULL),
	 (4024,'บ้านแฮด','Ban Haet',29,NULL,NULL),
	 (4025,'โนนศิลา','Non Sila',29,NULL,NULL),
	 (4026,'เวียงเก่า','Wiang Kao',29,NULL,NULL),
	 (4101,'เมืองอุดรธานี','Mueang Udon Thani',30,NULL,NULL),
	 (4102,'กุดจับ','Kut Chap',30,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (4103,'หนองวัวซอ','Nong Wua So',30,NULL,NULL),
	 (4104,'กุมภวาปี','Kumphawapi',30,NULL,NULL),
	 (4105,'โนนสะอาด','Non Sa-at',30,NULL,NULL),
	 (4106,'หนองหาน','Nong Saeng',30,NULL,NULL),
	 (4107,'ทุ่งฝน','Thung Fon',30,NULL,NULL),
	 (4108,'ไชยวาน','Chai Wan',30,NULL,NULL),
	 (4109,'ศรีธาตุ','Si That',30,NULL,NULL),
	 (4110,'วังสามหมอ','Wang Sam Mo',30,NULL,NULL),
	 (4111,'บ้านดุง','Ban Dung',30,NULL,NULL),
	 (4117,'บ้านผือ','Ban Phue',30,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (4118,'น้ำโสม','Nam Som',30,NULL,NULL),
	 (4119,'เพ็ญ','Phen',30,NULL,NULL),
	 (4120,'สร้างคอม','Sang Khom',30,NULL,NULL),
	 (4121,'หนองแสง','Nong Saeng',30,NULL,NULL),
	 (4122,'นายูง','Na Yung',30,NULL,NULL),
	 (4123,'พิบูลย์รักษ์','Phibun Rak',30,NULL,NULL),
	 (4124,'กู่แก้ว','Ku Kaeo',30,NULL,NULL),
	 (4125,'ประจักษ์ศิลปาคม','Prachaksinlapakhom',30,NULL,NULL),
	 (4201,'เมืองเลย','Mueang Loei',31,NULL,NULL),
	 (4202,'นาด้วง','Na Duang',31,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (4203,'เชียงคาน','Chiang Khan',31,NULL,NULL),
	 (4204,'ปากชม','Pak Chom',31,NULL,NULL),
	 (4205,'ด่านซ้าย','Dan Sai',31,NULL,NULL),
	 (4206,'นาแห้ว','Na Haeo',31,NULL,NULL),
	 (4207,'ภูเรือ','Phu Ruea',31,NULL,NULL),
	 (4208,'ท่าลี่','Tha Li',31,NULL,NULL),
	 (4209,'วังสะพุง','Wang Saphung',31,NULL,NULL),
	 (4210,'ภูกระดึง','Phu Kradueng',31,NULL,NULL),
	 (4211,'ภูหลวง','Phu Luang',31,NULL,NULL),
	 (4212,'ผาขาว','Pha  Khao',31,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (4213,'เอราวัณ','Erawan',31,NULL,NULL),
	 (4214,'หนองหิน','Nong Hin',31,NULL,NULL),
	 (4301,'เมืองหนองคาย','Mueang Nong Khai',32,NULL,NULL),
	 (4302,'ท่าบ่อ','Tha Bo',32,NULL,NULL),
	 (4305,'โพนพิสัย','Phon Phisai',32,NULL,NULL),
	 (4307,'ศรีเชียงใหม่','Si Chiang Mai',32,NULL,NULL),
	 (4308,'สังคม','Sangkhom',32,NULL,NULL),
	 (4314,'สระใคร','Sakhrai',32,NULL,NULL),
	 (4315,'เฝ้าไร่','Fao Rai',32,NULL,NULL),
	 (4316,'รัตนวาปี','Rattanawapi',32,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (4317,'โพธิ์ตาก','Pho Tak',32,NULL,NULL),
	 (4401,'เมืองมหาสารคาม','Mueang Maha Sarakham',33,NULL,NULL),
	 (4402,'แกดำ','Kae Dam',33,NULL,NULL),
	 (4403,'โกสุมพิสัย','Kosum Phisai',33,NULL,NULL),
	 (4404,'กันทรวิชัย','Kantharawichai',33,NULL,NULL),
	 (4405,'เชียงยืน','Chiang Yuen',33,NULL,NULL),
	 (4406,'บรบือ','Borabue',33,NULL,NULL),
	 (4407,'นาเชือก','Na Chueak',33,NULL,NULL),
	 (4408,'พยัคฆภูมิพิสัย','Phayakkhaphum Phisai',33,NULL,NULL),
	 (4409,'วาปีปทุม','Wapi Pathum',33,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (4410,'นาดูน','Na Dun',33,NULL,NULL),
	 (4411,'ยางสีสุราช','Yang Sisurat',33,NULL,NULL),
	 (4412,'กุดรัง','Kut Rang',33,NULL,NULL),
	 (4413,'ชื่นชม','Chuen Chom',33,NULL,NULL),
	 (4501,'เมืองร้อยเอ็ด','Mueang Roi Et',34,NULL,NULL),
	 (4502,'เกษตรวิสัย','Kaset Wisai',34,NULL,NULL),
	 (4503,'ปทุมรัตต์','Pathum Rat',34,NULL,NULL),
	 (4504,'จตุรพักตรพิมาน','Chaturaphak Phiman',34,NULL,NULL),
	 (4505,'ธวัชบุรี','Thawat Buri',34,NULL,NULL),
	 (4506,'พนมไพร','Phanom Phrai',34,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (4507,'โพนทอง','Phon Thong',34,NULL,NULL),
	 (4508,'โพธิ์ชัย','Pho Chai',34,NULL,NULL),
	 (4509,'หนองพอก','Nong Phok',34,NULL,NULL),
	 (4510,'เสลภูมิ','Selaphum',34,NULL,NULL),
	 (4511,'สุวรรณภูมิ','Suwannaphum',34,NULL,NULL),
	 (4512,'เมืองสรวง','Mueang Suang',34,NULL,NULL),
	 (4513,'โพนทราย','Phon Sai',34,NULL,NULL),
	 (4514,'อาจสามารถ','At Samat',34,NULL,NULL),
	 (4515,'เมยวดี','Moei Wadi',34,NULL,NULL),
	 (4516,'ศรีสมเด็จ','Si Somdet',34,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (4517,'จังหาร','Changhan',34,NULL,NULL),
	 (4518,'เชียงขวัญ','Chiang Khwan',34,NULL,NULL),
	 (4519,'หนองฮี','Nong Hi',34,NULL,NULL),
	 (4520,'ทุ่งเขาหลวง','Thung Khao Luang',34,NULL,NULL),
	 (4601,'เมืองกาฬสินธุ์','Mueang Kalasin',35,NULL,NULL),
	 (4602,'นามน','Na Mon',35,NULL,NULL),
	 (4603,'กมลาไสย','Kamalasai',35,NULL,NULL),
	 (4604,'ร่องคำ','Rong Kham',35,NULL,NULL),
	 (4605,'กุฉินารายณ์','Kuchinarai',35,NULL,NULL),
	 (4606,'เขาวง','Khao Wong',35,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (4607,'ยางตลาด','Yang Talat',35,NULL,NULL),
	 (4608,'ห้วยเม็ก','Huai Mek',35,NULL,NULL),
	 (4609,'สหัสขันธ์','Sahatsakhan',35,NULL,NULL),
	 (4610,'คำม่วง','Kham Muang',35,NULL,NULL),
	 (4611,'ท่าคันโท','Tha Khantho',35,NULL,NULL),
	 (4612,'หนองกุงศรี','Nong Kung Si',35,NULL,NULL),
	 (4613,'สมเด็จ','Somdet',35,NULL,NULL),
	 (4614,'ห้วยผึ้ง','Huai Phueng',35,NULL,NULL),
	 (4615,'สามชัย','Sam Chai',35,NULL,NULL),
	 (4616,'นาคู','Na Khu',35,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (4617,'ดอนจาน','Don Chan',35,NULL,NULL),
	 (4618,'ฆ้องชัย','Khong Chai',35,NULL,NULL),
	 (4701,'เมืองสกลนคร','Mueang Sakon Nakhon',36,NULL,NULL),
	 (4702,'กุสุมาลย์','Kusuman',36,NULL,NULL),
	 (4703,'กุดบาก','Kut Bak',36,NULL,NULL),
	 (4704,'พรรณานิคม','Phanna Nikhom',36,NULL,NULL),
	 (4705,'พังโคน','Phanh khon',36,NULL,NULL),
	 (4706,'วาริชภูมิ','Waritchaphum',36,NULL,NULL),
	 (4707,'นิคมน้ำอูน','Nikhom Nam un',36,NULL,NULL),
	 (4708,'วานรนิวาส','Wanon Niwat',36,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (4709,'คำตากล้า','Kham Ta Kla',36,NULL,NULL),
	 (4710,'บ้านม่วง','Ban Muang',36,NULL,NULL),
	 (4711,'อากาศอำนวย','Akat Amnuai',36,NULL,NULL),
	 (4712,'สว่างแดนดิน','Sawang Daen Din',36,NULL,NULL),
	 (4713,'ส่องดาว','Song Dao',36,NULL,NULL),
	 (4714,'เต่างอย','Tao Ngoi',36,NULL,NULL),
	 (4715,'โคกศรีสุพรรณ','Khok Si Suphan',36,NULL,NULL),
	 (4716,'เจริญศิลป์','Charoen Sin',36,NULL,NULL),
	 (4717,'โพนนาแก้ว','Phon Na Kaeo',36,NULL,NULL),
	 (4718,'ภูพาน','Phu Phan',36,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (4801,'เมืองนครพนม','Mueang Nakhon Phanom',37,NULL,NULL),
	 (4802,'ปลาปาก','Pla Pak',37,NULL,NULL),
	 (4803,'ท่าอุเทน','Tha Uthen',37,NULL,NULL),
	 (4804,'บ้านแพง','Ban Phaeng',37,NULL,NULL),
	 (4805,'ธาตุพนม','That Phanom',37,NULL,NULL),
	 (4806,'เรณูนคร','Renu Nakhon',37,NULL,NULL),
	 (4807,'นาแก','Na Kae',37,NULL,NULL),
	 (4808,'ศรีสงคราม','Si Songkhram',37,NULL,NULL),
	 (4809,'นาหว้า','Na Wa',37,NULL,NULL),
	 (4810,'โพนสวรรค์','Phon Sawan',37,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (4811,'นาทม','Na Thom',37,NULL,NULL),
	 (4812,'วังยาง','Wang Yang',37,NULL,NULL),
	 (4901,'เมืองมุกดาหาร','Mueang Mukdahan',38,NULL,NULL),
	 (4902,'นิคมคำสร้อย','Nikhom Kham Soi',38,NULL,NULL),
	 (4903,'ดอนตาล','Don Tan',38,NULL,NULL),
	 (4904,'ดงหลวง','Don Tan',38,NULL,NULL),
	 (4905,'คำชะอี','Khamcha-i',38,NULL,NULL),
	 (4906,'ว่านใหญ่','Wan Yai',38,NULL,NULL),
	 (4907,'หนองสูง','Nong Sung',38,NULL,NULL),
	 (5001,'เมืองเชียงใหม่','Mueang Chiang Mai',39,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (5002,'จอมทอง','Chom Thong',39,NULL,NULL),
	 (5003,'แม่แจ่ม','Mae Chaem',39,NULL,NULL),
	 (5004,'เชียงดาว','Chiang Dao',39,NULL,NULL),
	 (5005,'ดอยสะเก็ด','Doi Saket',39,NULL,NULL),
	 (5006,'แม่แตง','Mae Taeng',39,NULL,NULL),
	 (5007,'แม่ริม','Mae Rim',39,NULL,NULL),
	 (5008,'สะเมิง','Samoeng',39,NULL,NULL),
	 (5009,'ฝาง','Fang',39,NULL,NULL),
	 (5010,'แม่อาย','Mae Ai',39,NULL,NULL),
	 (5011,'พร้าว','Phrao',39,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (5012,'สันป่าตอง','San Pa Tong',39,NULL,NULL),
	 (5013,'สันกำแพง','San Kamphaeng',39,NULL,NULL),
	 (5014,'สันทราย','San Sai',39,NULL,NULL),
	 (5015,'หางดง','Hang Dong',39,NULL,NULL),
	 (5016,'ฮอด','Hot',39,NULL,NULL),
	 (5017,'ดอยเต่า','Doi Tao',39,NULL,NULL),
	 (5018,'อมก๋อย','Omkoi',39,NULL,NULL),
	 (5019,'สารภี','Saraphi',39,NULL,NULL),
	 (5020,'เวียงแหง','Wiang Haeng',39,NULL,NULL),
	 (5021,'ไชยปราการ','Chai Prakan',39,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (5022,'แม่วาง','Mae Wang',39,NULL,NULL),
	 (5023,'แม่ออน','Mae On',39,NULL,NULL),
	 (5024,'ดอยหล่อ','Doi Lo',39,NULL,NULL),
	 (5025,'กัลยาณิวัฒนา','Kanlayaniwatthana',39,NULL,NULL),
	 (5101,'เมืองลำพูน','Mueang Lamphun',40,NULL,NULL),
	 (5102,'แม่ทา','Mae Tha',40,NULL,NULL),
	 (5103,'บ้านโฮ่ง','Ban Hong',40,NULL,NULL),
	 (5104,'ลี้','Li',40,NULL,NULL),
	 (5105,'ทุ่งหัวช้าง','Thung Hua Chang',40,NULL,NULL),
	 (5106,'ป่าซาง','Pa Sang',40,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (5107,'บ้านธิ','Ban Thi',40,NULL,NULL),
	 (5108,'เวียงหนองล่อง','Wiang Nong Long',40,NULL,NULL),
	 (5201,'เมืองลำปาง','Mueang Lampang',41,NULL,NULL),
	 (5202,'แม่เมาะ','Mae Mo',41,NULL,NULL),
	 (5203,'เกาะคา','Ko kha',41,NULL,NULL),
	 (5204,'เสริมงาม','Soem Ngam',41,NULL,NULL),
	 (5205,'งาว','Ngao',41,NULL,NULL),
	 (5206,'แจ้ห่ม','Chae Hom',41,NULL,NULL),
	 (5207,'วังเหนือ','Wang Nuea',41,NULL,NULL),
	 (5208,'เถิน','Thoen',41,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (5209,'แม่พริก','Mae Phrik',41,NULL,NULL),
	 (5210,'แม่ทะ','Mae Tha',41,NULL,NULL),
	 (5211,'สบปราบ','Sop Prap',41,NULL,NULL),
	 (5212,'ห้างฉัตร','Hang Chat',41,NULL,NULL),
	 (5213,'เมืองปาน','Mueang Pan',41,NULL,NULL),
	 (5301,'เมืองอุตรดิตถ์','Mueang Uttaradit',42,NULL,NULL),
	 (5302,'ตรอน','Tron',42,NULL,NULL),
	 (5303,'ท่าปลา','Tha Pla',42,NULL,NULL),
	 (5304,'น้ำปาด','Nam Pat',42,NULL,NULL),
	 (5305,'ฟากท่า','Fak Tha',42,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (5306,'บ้านโคก','Ban Khok',42,NULL,NULL),
	 (5307,'พิชัย','Phichai',42,NULL,NULL),
	 (5308,'ลับแล','Laplae',42,NULL,NULL),
	 (5309,'ทองแสนขัน','Thong Saen Khan',42,NULL,NULL),
	 (5401,'เมืองแพร่','Mueang Phrae',43,NULL,NULL),
	 (5402,'ร้องกวาง','Mueang Phrae',43,NULL,NULL),
	 (5403,'ลอง','Long',43,NULL,NULL),
	 (5404,'สูงเม่น','Sung Men',43,NULL,NULL),
	 (5405,'เด่นชัย','Den Chai',43,NULL,NULL),
	 (5406,'สอง','Song',43,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (5407,'วังชิ้น','Wang Chin',43,NULL,NULL),
	 (5408,'หนองม่วงไข่','Nong Muang Khai',43,NULL,NULL),
	 (5501,'เมืองน่าน','Mueang Nan',44,NULL,NULL),
	 (5502,'แม่จริม','Mae Charim',44,NULL,NULL),
	 (5503,'บ้านหลวง','Ban Luang',44,NULL,NULL),
	 (5504,'นาน้อย','Na Noi',44,NULL,NULL),
	 (5505,'ปัว','Pua',44,NULL,NULL),
	 (5506,'ท่าวังผา','Tha Wang Pha',44,NULL,NULL),
	 (5507,'เวียงสา','Wiang Sa',44,NULL,NULL),
	 (5508,'ทุ่งช้าง','Thung Chang',44,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (5509,'เชียงกลาง','Chiang Klang',44,NULL,NULL),
	 (5510,'นาหมื่น','Na Muen',44,NULL,NULL),
	 (5511,'สันติสุข','Santi Suk',44,NULL,NULL),
	 (5512,'บ่อเกลือ','Bo Kluea',44,NULL,NULL),
	 (5513,'สองแคว','Song Khwae',44,NULL,NULL),
	 (5514,'ภูเพียง','Phu Phiang',44,NULL,NULL),
	 (5515,'เฉลิมพระเกียรติ','Chaloem Phra Kiet',44,NULL,NULL),
	 (5601,'เมืองพะเยา','Mueang Phayao',45,NULL,NULL),
	 (5602,'จุน','Mueang Phayao',45,NULL,NULL),
	 (5603,'เชียงคำ','Mueang Phayao',45,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (5604,'เชียงม่วน','Mueang Phayao',45,NULL,NULL),
	 (5605,'ดอกคำใต้','Mueang Phayao',45,NULL,NULL),
	 (5606,'ปง','Mueang Phayao',45,NULL,NULL),
	 (5607,'แม่ใจ','Mueang Phayao',45,NULL,NULL),
	 (5608,'ภูซาง','Mueang Phayao',45,NULL,NULL),
	 (5609,'ภูกามยาว','Mueang Phayao',45,NULL,NULL),
	 (5701,'เมืองเชียงราย','Mueang Chiang Rai',46,NULL,NULL),
	 (5702,'เวียงชัย','Wiang Chai',46,NULL,NULL),
	 (5703,'เชียงของ','Chiang Khong',46,NULL,NULL),
	 (5704,'เทิง','Thoeng',46,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (5705,'พาน','Phan',46,NULL,NULL),
	 (5706,'ป่าแดด','Pa Daet',46,NULL,NULL),
	 (5707,'แม่จัน','Mae Chan',46,NULL,NULL),
	 (5708,'เชียงแสน','Chiang Saen',46,NULL,NULL),
	 (5709,'แม่สาย','Mae Sai',46,NULL,NULL),
	 (5710,'แม่สรวย','Mae Suai',46,NULL,NULL),
	 (5711,'เวียงป่าเป้า','Wiang Pa Pao',46,NULL,NULL),
	 (5712,'พญาเม็งราย','Phaya Mengrai',46,NULL,NULL),
	 (5713,'เวียงแก่น','Wiang Kaen',46,NULL,NULL),
	 (5714,'ขุนตาล','Khun Tan',46,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (5715,'แม่ฟ้าหลวง','Mae Fa Luang',46,NULL,NULL),
	 (5716,'แม่ลาว','Mae Lao',46,NULL,NULL),
	 (5717,'เวียงเชียงรุ้ง','Wiang Chiang Rung',46,NULL,NULL),
	 (5718,'ดอยหลวง','Doi Luang',46,NULL,NULL),
	 (5801,'เมืองแม่ฮ่องสอน','Mueang Mae Hong Son',47,NULL,NULL),
	 (5802,'ขุนยวม','Khun Yuam',47,NULL,NULL),
	 (5803,'ปาย','Pai',47,NULL,NULL),
	 (5804,'แม่สะเรียง','Mae Sariang',47,NULL,NULL),
	 (5805,'แม่ลาน้อย','Mae La Noi',47,NULL,NULL),
	 (5806,'สบเมย','Sop Moei',47,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (5807,'ปางมะผ้า','Pang Mapha',47,NULL,NULL),
	 (6001,'เมืองนครสวรรค์','Mueang Nakhon Sawan',48,NULL,NULL),
	 (6002,'โกรกพระ','Krok Phra',48,NULL,NULL),
	 (6003,'ชุมแสง','Chum Saeng',48,NULL,NULL),
	 (6004,'หนองบัว','Nong Bua',48,NULL,NULL),
	 (6005,'บรรพตพิสัย','Banphot Phisai',48,NULL,NULL),
	 (6006,'เก้าเลี้ยว','Kao Liao',48,NULL,NULL),
	 (6007,'ตาคลี','Takhli',48,NULL,NULL),
	 (6008,'ท่าตะโก','Tha Tako',48,NULL,NULL),
	 (6009,'ไพศาลี','Phaisali',48,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (6010,'พยุหะคีรี','Phayuha Hkiri',48,NULL,NULL),
	 (6011,'ลาดยาว','Lat Yao',48,NULL,NULL),
	 (6012,'ตากฟ้า','Tak Fa',48,NULL,NULL),
	 (6013,'แม่วงก์','Mae Wong',48,NULL,NULL),
	 (6014,'แม่เปิน','Mae Pern',48,NULL,NULL),
	 (6015,'ชุมตาบง','Chum Ta Bong',48,NULL,NULL),
	 (6101,'เมืองอุทัยธานี','Mueang Uthai Thani',49,NULL,NULL),
	 (6102,'ทัพทัน','Thap Than',49,NULL,NULL),
	 (6103,'สว่างอารมณ์','Sawang Arom',49,NULL,NULL),
	 (6104,'หนองฉาง','Nong Chang',49,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (6105,'หนองขาหย่าง','Nong Khayang',49,NULL,NULL),
	 (6106,'บ้านไร่','Ban Rai',49,NULL,NULL),
	 (6107,'ลานสัก','Lan Sak',49,NULL,NULL),
	 (6108,'ห้วยคต','Huai Khot',49,NULL,NULL),
	 (6201,'เมืองกำแพงเพชร','Mueang Kamphaeng Phet',50,NULL,NULL),
	 (6202,'ไทรงาม','Sai Ngam',50,NULL,NULL),
	 (6203,'คลองลาน','Khlong Lan',50,NULL,NULL),
	 (6204,'ขาณุวรลักษบุรี','Khanu Woralaksaburi',50,NULL,NULL),
	 (6205,'คลองขลุง','Khlong Khlung',50,NULL,NULL),
	 (6206,'พรานกระต่าย','Phran Kratai',50,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (6207,'ลานกระบือ','Lan Krabue',50,NULL,NULL),
	 (6208,'ทรายทองวัฒนา','Sai Thong Watthana',50,NULL,NULL),
	 (6209,'ปางศิลาทอง','Pang Sila Thong',50,NULL,NULL),
	 (6210,'บึงสามัคคี','Bueng Samakkhi',50,NULL,NULL),
	 (6211,'โกสัมพีนคร','Kosamphi Nakhon',50,NULL,NULL),
	 (6301,'เมืองตาก','Mueang Tak',51,NULL,NULL),
	 (6302,'บ้านตาก','Ban Tak',51,NULL,NULL),
	 (6303,'สามเงา','Sam Ngao',51,NULL,NULL),
	 (6304,'แม่ระมาด','Mae Ramat',51,NULL,NULL),
	 (6305,'ท่าสองยาง','Tha Song Yang',51,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (6306,'แม่สอด','Mae Sot',51,NULL,NULL),
	 (6307,'พบพระ','Phop Phra',51,NULL,NULL),
	 (6308,'อุ้มผาง','Um Phang',51,NULL,NULL),
	 (6309,'วังเจ้า','Wang Chao',51,NULL,NULL),
	 (6401,'เมืองสุโขทัย','Mueang Sukhothai',52,NULL,NULL),
	 (6402,'บ้านด่านลานหอย','Ban Dan Lan Hoi',52,NULL,NULL),
	 (6403,'คีรีมาศ','Khiri Mat',52,NULL,NULL),
	 (6404,'กงไกรลาศ','Kong Krailat',52,NULL,NULL),
	 (6405,'ศรีสัชนาลัย','Si Satchanalai',52,NULL,NULL),
	 (6406,'ศรีสำโรง','Si Samrong',52,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (6407,'สวรรคโลก','Sawankhalok',52,NULL,NULL),
	 (6408,'ศรีนคร','Si Nakhon',52,NULL,NULL),
	 (6409,'ทุ่งเสลี่ยม','Thung Saliam',52,NULL,NULL),
	 (6501,'เมืองพิษณุโลก','Mueang Phitsanulok',53,NULL,NULL),
	 (6502,'นครไทย','Nakhon Thai',53,NULL,NULL),
	 (6503,'ชาติตระการ','Chat Trakan',53,NULL,NULL),
	 (6504,'บางระกำ','Bang Rakam',53,NULL,NULL),
	 (6505,'บางกระทุ่ม','Bang Krathum',53,NULL,NULL),
	 (6506,'พรหมพิราม','Phrom Phiram',53,NULL,NULL),
	 (6507,'วัดโบสถ์','Wat Bot',53,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (6508,'วังทอง','Wang Thong',53,NULL,NULL),
	 (6509,'เนินมะปราง','Noen Maprang',53,NULL,NULL),
	 (6601,'เมืองพิจิตร','Mueang Phichit',54,NULL,NULL),
	 (6602,'วังทรายพูน','Wang Sai Phun',54,NULL,NULL),
	 (6603,'โพธิ์ประทับช้าง','Pho Prathap Chang',54,NULL,NULL),
	 (6604,'ตะพานหิน','Taphan Hin',54,NULL,NULL),
	 (6605,'บางมูลนาก','Bang Mun Nak',54,NULL,NULL),
	 (6606,'โพทะเล','Pho Thale',54,NULL,NULL),
	 (6607,'สามง่าม','Sam Ngam',54,NULL,NULL),
	 (6608,'ทับคล้อ','Tap Khlo',54,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (6609,'สากเหล็ก','Sak Lek',54,NULL,NULL),
	 (6610,'บึงนาราง','Bueng Na Rang',54,NULL,NULL),
	 (6611,'ดงเจริญ','Dong Charoen',54,NULL,NULL),
	 (6612,'วชิรบารมี','Wachirabarami',54,NULL,NULL),
	 (6701,'เมืองเพชรบูรณ์','Mueang Phetchabun',55,NULL,NULL),
	 (6702,'ชนแดน','Chon Daen',55,NULL,NULL),
	 (6703,'หล่มสัก','Lom Sak',55,NULL,NULL),
	 (6704,'หล่มเก่า','Lom Kao',55,NULL,NULL),
	 (6705,'วิเชียรบุรี','Wichian Buri',55,NULL,NULL),
	 (6706,'ศรีเทพ','Si Thep',55,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (6707,'หนองไผ่','Nong Phai',55,NULL,NULL),
	 (6708,'บึงสามพัน','Bueng Sam Phan',55,NULL,NULL),
	 (6709,'น้ำหนาว','Nam Nao',55,NULL,NULL),
	 (6710,'วังโป่ง','Wang Pong',55,NULL,NULL),
	 (6711,'เขาค้อ','Khao kho',55,NULL,NULL),
	 (7001,'เมืองราชบุรี','Mueang Ratchaburi',56,NULL,NULL),
	 (7002,'จอมบึง','Chom Bueng',56,NULL,NULL),
	 (7003,'สวนผึ้ง','Suan Phueng',56,NULL,NULL),
	 (7004,'ดำเนินสะดวก','Damnoen Saduak',56,NULL,NULL),
	 (7005,'บ้านโป่ง','Ban Pong',56,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (7006,'บางแพ','Bang Phae',56,NULL,NULL),
	 (7007,'โพธาราม','Photharam',56,NULL,NULL),
	 (7008,'ปากท่อ','Pak Tho',56,NULL,NULL),
	 (7009,'วัดเพลง','Wat Phleng',56,NULL,NULL),
	 (7010,'บ้านคา','Ban Kha',56,NULL,NULL),
	 (7101,'เมืองกาญจนบุรี','Mueang Kanchanaburi',57,NULL,NULL),
	 (7102,'ไทรโยค','Sai Yok',57,NULL,NULL),
	 (7103,'บ่อพลอย','Bo Phloi',57,NULL,NULL),
	 (7104,'ศรีสวัสดิ์','Si Sawat',57,NULL,NULL),
	 (7105,'ท่ามะกา','Tha Maka',57,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (7106,'ท่าม่วง','Tha Muang',57,NULL,NULL),
	 (7107,'ทองผาภูมิ','Thong Pha Phum',57,NULL,NULL),
	 (7108,'สังขละบุรี','Sangkhla Buri',57,NULL,NULL),
	 (7109,'พนมทวน','Phanom Thuan',57,NULL,NULL),
	 (7110,'เลาขวัญ','Lao Khwan',57,NULL,NULL),
	 (7111,'ด่านมะขามเตี้ย','Dan Makham Tia',57,NULL,NULL),
	 (7112,'หนองปรือ','Nong Prue',57,NULL,NULL),
	 (7113,'ห้วยกระเจา','Huai Krachao',57,NULL,NULL),
	 (7201,'เมืองสุพรรณบุรี','Mueang Saphan Buri',58,NULL,NULL),
	 (7202,'เดิมบางนางบวช','Doem Bang Nang Buat',58,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (7203,'ด่านช้าง','Dan Chang',58,NULL,NULL),
	 (7204,'บางปลาม้า','Bang Pla Ma',58,NULL,NULL),
	 (7205,'ศรีประจันต์','Si Prachan',58,NULL,NULL),
	 (7206,'ดอนเจดีย์','Don Chedi',58,NULL,NULL),
	 (7207,'สองพี่น้อง','Song Phi Nong',58,NULL,NULL),
	 (7208,'สามชุก','Sam Chuk',58,NULL,NULL),
	 (7209,'อู่ทอง','U Thong',58,NULL,NULL),
	 (7210,'หนองหญ้าไซ','Nong Ya Sai',58,NULL,NULL),
	 (7301,'เมืองนครปฐม','mueang Nakhon Pathom',59,NULL,NULL),
	 (7302,'กำแพงแสน','Kamphaeng Saen',59,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (7303,'นครชัยศรี','Nakhon Chai Si',59,NULL,NULL),
	 (7304,'ดอนตูม','Don Tum',59,NULL,NULL),
	 (7305,'บางเลน','Bang Len',59,NULL,NULL),
	 (7306,'สามพราน','Sam Phran',59,NULL,NULL),
	 (7307,'พุทธมณฑล','Phutthamonthon',59,NULL,NULL),
	 (7401,'เมืองสมุทรสาคร','Mueang Samut Sakhon',60,NULL,NULL),
	 (7402,'กระทุ่มแบน','Krathum Baen',60,NULL,NULL),
	 (7403,'บ้านแพ้ว','Ban Phaeo',60,NULL,NULL),
	 (7501,'เมืองสมุทรสงคราม','Mueang Samut Songkhram',61,NULL,NULL),
	 (7502,'บางคนที','Bang Khonthi',61,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (7503,'อัมพวา','Amphawa',61,NULL,NULL),
	 (7601,'เมืองเพชรบุรี','Mueang Phetchaburi',62,NULL,NULL),
	 (7602,'เขาย้อย','Khao Yoi',62,NULL,NULL),
	 (7603,'หนองหญ้าปล้อง','Nong Ya Plong',62,NULL,NULL),
	 (7604,'ชะอำ','Cha-am',62,NULL,NULL),
	 (7605,'ท่ายาง','Tha Yang',62,NULL,NULL),
	 (7606,'บ้านลาด','Ban Lat',62,NULL,NULL),
	 (7607,'บ้านแหลม','Ban Laem',62,NULL,NULL),
	 (7608,'แก่งกระจาน','Kaeng Krachan',62,NULL,NULL),
	 (7701,'เมืองประจวบคีรีขันธ์','Mueang Prachuap Khiri Khan',63,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (7702,'กุยบุรี','Kui Buri',63,NULL,NULL),
	 (7703,'ทับสะแก','Thap Sakae',63,NULL,NULL),
	 (7704,'บางสะพาน','Bang Saphan',63,NULL,NULL),
	 (7705,'บางสะพานน้อย','Bang Saphan Noi',63,NULL,NULL),
	 (7706,'ปราณบุรี','Pran Buri',63,NULL,NULL),
	 (7707,'หัวหิน','Hua Hin',63,NULL,NULL),
	 (7708,'สามร้อยยอด','Sam Roi Yot',63,NULL,NULL),
	 (8001,'เมืองนครศรีธรรมราช','Mueang Nakhon Si Thammarat',64,NULL,NULL),
	 (8002,'พรหมคีรี','Phrom Khiri',64,NULL,NULL),
	 (8003,'ลานสกา','Lan Saka',64,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (8004,'ฉวาง','Chawang',64,NULL,NULL),
	 (8005,'พิปูน','Phipun',64,NULL,NULL),
	 (8006,'เชียรใหญ่','Chian Yai',64,NULL,NULL),
	 (8007,'ชะอวด','Cha-uat',64,NULL,NULL),
	 (8008,'ท่าศาลา','Tha Sala',64,NULL,NULL),
	 (8009,'ทุ่งสง','Thung Song',64,NULL,NULL),
	 (8010,'นาบอน','Na Bon',64,NULL,NULL),
	 (8011,'ทุ่งใหญ่','Thung Yai',64,NULL,NULL),
	 (8012,'ปากพนัง','Pak Phanang',64,NULL,NULL),
	 (8013,'ร่อนพิบูลย์','Ron Phibun',64,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (8014,'สิชล','Sichon',64,NULL,NULL),
	 (8015,'ขนอม','Khanom',64,NULL,NULL),
	 (8016,'หัวไทร','Hua Sai',64,NULL,NULL),
	 (8017,'บางขัน','Bang Khan',64,NULL,NULL),
	 (8018,'ถ้ำพรรณรา','Tham Phannara',64,NULL,NULL),
	 (8019,'จุฬาภรณ์','Chulabhorn',64,NULL,NULL),
	 (8020,'พระพรหม','Phra Phrom',64,NULL,NULL),
	 (8021,'นบพิตำ','Nopphitam',64,NULL,NULL),
	 (8022,'ช้างกลาง','Chang Klang',64,NULL,NULL),
	 (8023,'เฉลิมพระเกียรติ','Chaloem Phra Kiet',64,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (8101,'เมืองกระบี่','Mueang Krabi',65,NULL,NULL),
	 (8102,'เขาพนม','Khao Phanom',65,NULL,NULL),
	 (8103,'เกาะลันตา','Ko Lanta',65,NULL,NULL),
	 (8104,'คลองท่อม','Khlong Thom',65,NULL,NULL),
	 (8105,'อ่าวลึก','Ao Luek',65,NULL,NULL),
	 (8106,'ปลายพระยา','Plai Phraya',65,NULL,NULL),
	 (8107,'ลำทับ','Lam Thap',65,NULL,NULL),
	 (8108,'เหนือคลอง','Nuea Khlong',65,NULL,NULL),
	 (8201,'เมืองพังงา','Mueang Phang-nga',66,NULL,NULL),
	 (8202,'เกาะยาว','Ko Yao',66,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (8203,'กะปง','Kapong',66,NULL,NULL),
	 (8204,'ตะกั่วทุ่ง','Takua Thung',66,NULL,NULL),
	 (8205,'ตะกั่วป่า','Takua Pa',66,NULL,NULL),
	 (8206,'คุระบุรี','Khura Buri',66,NULL,NULL),
	 (8207,'ทับปุด','Thap Put',66,NULL,NULL),
	 (8208,'ท้ายเหมือง','Thai Mueang',66,NULL,NULL),
	 (8301,'เมืองภูเก็ต','Mueang Phuket',67,NULL,NULL),
	 (8302,'กะทู้','Kathu',67,NULL,NULL),
	 (8303,'ถลาง','Thalang',67,NULL,NULL),
	 (8401,'เมืองสุราษฎร์ธานี','Mueang Surat Thani',68,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (8402,'กาญจนดิษฐ์','Kanchanadit',68,NULL,NULL),
	 (8403,'ดอนสัก','Don Sak',68,NULL,NULL),
	 (8404,'เกาะสมุย','Ko Samui',68,NULL,NULL),
	 (8405,'เกาะพะงัน','Ko Pha-ngan',68,NULL,NULL),
	 (8406,'ไชยา','Chaiya',68,NULL,NULL),
	 (8407,'ท่าชนะ','Tha Chana',68,NULL,NULL),
	 (8408,'คีรีรัฐนิคม','Khiri Rat Nikhom',68,NULL,NULL),
	 (8409,'บ้านตาขุน','Ban Ta Khun',68,NULL,NULL),
	 (8410,'พนม','Phanom',68,NULL,NULL),
	 (8411,'ท่าฉาง','Tha Chang',68,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (8412,'บ้านนาสาร','Ban Na San',68,NULL,NULL),
	 (8413,'บ้านนาเดิม','Ban Na Doem',68,NULL,NULL),
	 (8414,'เคียนซา','Khian Sa',68,NULL,NULL),
	 (8415,'เวียงสระ','Wiang Sa',68,NULL,NULL),
	 (8416,'พระแสง','Phrasaeng',68,NULL,NULL),
	 (8417,'พุนพิน','Phunphin',68,NULL,NULL),
	 (8418,'ชัยบุรี','Chai Buri',68,NULL,NULL),
	 (8419,'วิภาวดี','Chai Buri',68,NULL,NULL),
	 (8501,'เมืองระนอง','Mueang Ranong',69,NULL,NULL),
	 (8502,'ละอุ่น','La-un',69,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (8503,'กะเปอร์','Papoe',69,NULL,NULL),
	 (8504,'กระบุรี','Kra Buri',69,NULL,NULL),
	 (8505,'สุขสำราญ','Suk Samran',69,NULL,NULL),
	 (8601,'เมืองชุมพร','Mueang Chumphon',70,NULL,NULL),
	 (8602,'ท่าแซะ','Tha Sae',70,NULL,NULL),
	 (8603,'ปะทิว','Pathio',70,NULL,NULL),
	 (8604,'หลังสวน','Lang Suan',70,NULL,NULL),
	 (8605,'ละแม','Lamae',70,NULL,NULL),
	 (8606,'พะโต๊ะ','Phato',70,NULL,NULL),
	 (8607,'สวี','Sawi',70,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (8608,'ทุ่งตะโก','Thung Tako',70,NULL,NULL),
	 (9001,'เมืองสงขลา','Muaeng Songkhla',71,NULL,NULL),
	 (9002,'สทิงพระ','Sathing Phra',71,NULL,NULL),
	 (9003,'จะนะ','Chana',71,NULL,NULL),
	 (9004,'นาทวี','Na Thawi',71,NULL,NULL),
	 (9005,'เทพา','Thepha',71,NULL,NULL),
	 (9006,'สะบ้าย้อย','Saba Yoi',71,NULL,NULL),
	 (9007,'ระโนด','Ranot',71,NULL,NULL),
	 (9008,'กระแสสินธุ์','Krasae Sin',71,NULL,NULL),
	 (9009,'รัตภูมิ','Rattaphum',71,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (9010,'สะเดา','Sadao',71,NULL,NULL),
	 (9011,'หาดใหญ่','Hat Yai',71,NULL,NULL),
	 (9012,'นาหม่อม','Na Mom',71,NULL,NULL),
	 (9013,'ควนเนียง','Khuan Niang',71,NULL,NULL),
	 (9014,'บางกล่ำ','Bang Klam',71,NULL,NULL),
	 (9015,'สิงหนคร','Singhanakhon',71,NULL,NULL),
	 (9016,'คลองหอยโข่ง','Khlong Hoi Khong',71,NULL,NULL),
	 (9101,'เมืองสตูล','Mueang Satun',72,NULL,NULL),
	 (9102,'ควนโดน','Khuan Don',72,NULL,NULL),
	 (9103,'ควนกาหลง','Khuan Kalong',72,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (9104,'ท่าแพ','Tha Phae',72,NULL,NULL),
	 (9105,'ละงู','La-ngu',72,NULL,NULL),
	 (9106,'ทุ่งหว้า','Thung  Wa',72,NULL,NULL),
	 (9107,'มะนัง','Manang',72,NULL,NULL),
	 (9201,'เมืองตรัง','Mueang Trang',73,NULL,NULL),
	 (9202,'กันตัง','Kantang',73,NULL,NULL),
	 (9203,'ย่านตาขาว','Yan Ta Khao',73,NULL,NULL),
	 (9204,'ปะเหลียน','Palian',73,NULL,NULL),
	 (9205,'สิเกา','Sikao',73,NULL,NULL),
	 (9206,'ห้วยยอด','Huai Yot',73,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (9207,'วังวิเศษ','Wang Wiset',73,NULL,NULL),
	 (9208,'นาโยง','Na Yong',73,NULL,NULL),
	 (9209,'รัษฎา','Ratsada',73,NULL,NULL),
	 (9210,'หาดสำราญ','Hat Samran',73,NULL,NULL),
	 (9301,'เมืองพัทลุง','Mueang Phatthalung',74,NULL,NULL),
	 (9302,'กงหรา','Kong Ra',74,NULL,NULL),
	 (9303,'เขาชัยสน','Khao Chaison',74,NULL,NULL),
	 (9304,'ตะโหมด','Tamot',74,NULL,NULL),
	 (9305,'ควนขนุน','Khuan Khanun',74,NULL,NULL),
	 (9306,'ปากพะยูน','Pak Phayun',74,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (9307,'ศรีบรรพต','Si Banphot',74,NULL,NULL),
	 (9308,'ป่าบอน','Pa Bon',74,NULL,NULL),
	 (9309,'บางแก้ว','Bang Kaeo',74,NULL,NULL),
	 (9310,'ป่าพยอม','Pa Phayom',74,NULL,NULL),
	 (9311,'ศรีนครินทร์','Srinagarindra',74,NULL,NULL),
	 (9401,'เมืองปัตตานี','Mueang Pattani',75,NULL,NULL),
	 (9402,'โคกโพธิ์','Khok Pho',75,NULL,NULL),
	 (9403,'หนองจิก','Nong Chik',75,NULL,NULL),
	 (9404,'ปะนาเระ','Panare',75,NULL,NULL),
	 (9405,'มายอ','Mayo',75,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (9406,'ทุ่งยางแดง','Thung Yang Daeng',75,NULL,NULL),
	 (9407,'สายบุรี','Sai Buri',75,NULL,NULL),
	 (9408,'ไม้แก่น','Mai Kaen',75,NULL,NULL),
	 (9409,'ยะหริ่ง','Yaring',75,NULL,NULL),
	 (9410,'ยะรัง','Yarang',75,NULL,NULL),
	 (9411,'กะพ้อ','Kapho',75,NULL,NULL),
	 (9412,'แม่ลาน','Mae Lan',75,NULL,NULL),
	 (9501,'เมืองยะลา','Mueang Yala',76,NULL,NULL),
	 (9502,'เบตง','Betong',76,NULL,NULL),
	 (9503,'บันนังสตา','Bannang Sata',76,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (9504,'ธารโต','Than To',76,NULL,NULL),
	 (9505,'ยะหา','Yaha',76,NULL,NULL),
	 (9506,'รามัน','Raman',76,NULL,NULL),
	 (9507,'กาบัง','Kabang',76,NULL,NULL),
	 (9508,'กรงปีนัง','Krong Pinang',76,NULL,NULL),
	 (9601,'เมืองนราธิวาส','Mueang Narathiwat',77,NULL,NULL),
	 (9602,'ตากใบ','Tak Bai',77,NULL,NULL),
	 (9603,'บาเจาะ','Tak Bai',77,NULL,NULL),
	 (9604,'ยี่งอ','Yi-ngo',77,NULL,NULL),
	 (9605,'ระแงะ','Ra-ngae',77,NULL,NULL);
INSERT INTO public.districts (code,name_in_thai,name_in_english,province_id,created_at,updated_at) VALUES
	 (9606,'รือเสาะ','Rueso',77,NULL,NULL),
	 (9607,'ศรีสาคร','Si Sakhon',77,NULL,NULL),
	 (9608,'แว้ง','Waeng',77,NULL,NULL),
	 (9609,'สุคิริน','Sukhirin',77,NULL,NULL),
	 (9610,'สุไหงโก-ลก','Su-ngai Kolok',77,NULL,NULL),
	 (9611,'สุไหงปาดี','Su-ngai Padi',77,NULL,NULL),
	 (9612,'จะแนะ','Chanae',77,NULL,NULL),
	 (9613,'เจาะไอร้อง','Cho-airong',77,NULL,NULL);
